version: '3.9'

services:
  # backend:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - database

  database:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'innovation'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
